### ISSUE TITLE
to_currency with cents false seem to be broken

### ISSUE THREAD

**Issue by shulcsm** [savoirfairelinux/num2words#104]
`to_currency` form that takes `currency` as argument with `cents=False` seem to produce unexpected results when there is not enough precision available.

For instance `num2words(Decimal('38.4'), lang='lv', to='currency', seperator=' un', cents=False, currency='EUR)` results in `Trīsdesmit astoņi euro un 04 centi`.

Is this expected behaviour? All converters that support this form seem to be affected.

`left, right = n.split('.')` seems to be too naive for right part since it doesn't respect position.

**Comment by erozqba** [comment]
@shulcsm in fact, the code for converting to currencies that exist, is old code that was not actually maintained. It was not supported by the num2words.num2words wrapper function. This was written by the previous maintainer of the library (not Savoir-faire Linux). So we will need to find and fix the hidden problems in this part of the code. We also need more tests for it, because right now there are almost any.
So pull requests are welcomed!

**Comment by shulcsm** [comment]
@erozqba I'm not sure what is the old and what is new. What is the expected API(public and private) for `to_currency`. Since  now there seem to be two variants `to_currency(self, val, longval=True)` bound to one particular currency and calling `to_splitnum` and more involved one `to_currency(n, currency='EUR', cents=True, seperator=',')`. There also seem to be a lot of code duplication.

**Comment by erozqba** [comment]
@shulcsm you are certainly right, we should define a proper API and fix this, looks like different persons have implemented it differently. I'm just taking over a former colleague to maintain the project and not let it die again, so I don't know all the history that has caused the actual code state.
Could you propose some improves in a PR? 
Pull request are always welcomed.

Thanks a lot for taking the time to collaborate in this project.

If you have time could you check the PR #105  and let me know if that looks OK to you?
