### ISSUE TITLE
Can I help in adding Hungarian language ?

### ISSUE THREAD

**Issue by xcom169** [savoirfairelinux/num2words#317]
Can I help to the project in adding Hungarian language ?

**Comment by ventilooo** [comment]
Yes for sure, any contribution is welcome.
You got plenty of PR to take example from.
Please submit test with your code.

**Comment by xcom169** [comment]
So currently HU language is totally unsupported in the latest version ? Because I've seen some source files for HU.

**Comment by ventilooo** [comment]
@xcom169 

There's some basic support on the master branch.
Since that initial contribution, no new version has been released.
So you can either setup you package manager to fetch from source instead of PyPi and use it in your project.
Otherwise polish the current implementation for the next release.
