### ISSUE TITLE
Italian trillion problem 

### ISSUE THREAD

**Issue by javidh** [savoirfairelinux/num2words#368]
input: 257,550,000,000,000
language italian

### Expected Behaviour

duecentocinquantasette trilioni cinquecentocinquanta miliardi

### Actual Behaviour

duecentocinquantasette bilioni e cinquecentocinquanta miliardi

### Steps to reproduce

Just run `n2words(257550000000000, {lang: 'it'})`

**Comment by neysofu** [comment]
Hi @javidh, I'm the one who wrote the current version of the Italian module.

I believe the current behavior is correct. In Italian, a "bilione" is defined as 10<sup>12</sup>, You can find more information the Wikipedia [article](https://it.wikipedia.org/wiki/Bilione): this is because in Italy we use the long scale system. A "trilione" would be 10<sup>15</sup>.

**Comment by javidh** [comment]
Hi @neysofu, thanks for the explanantion. So [google translate](https://translate.google.com/?sl=it&tl=en&text=duecentocinquantasette%20bilioni%20e%20cinquecentocinquanta%20miliardi%0A%0A&op=translate) was wrong. Thanks!

**Comment by neysofu** [comment]
Yup, I guess it confuses between the strikingly similar "billions" and "bilioni", even though they're not the same number :)
