### ISSUE TITLE
0.5.4 installation is failing

### ISSUE THREAD

**Issue by ypraveen** [savoirfairelinux/num2words#53]
root@avi-dev:/tmp/tt# /tmp/tt/bin/pip install num2words
Downloading/unpacking num2words
  Downloading num2words-0.5.4-py2-none-any.whl (94kB): 94kB downloaded
Installing collected packages: num2words
Cleaning up...
num2words is in an unsupported or invalid wheel
Storing debug log for failure in /root/.pip/pip.log

**Comment by ypraveen** [comment]
root@avi-dev:/tmp/tt# /tmp/tt/bin/pip --version
pip 1.5.4 from /tmp/tt/local/lib/python2.7/site-packages (python 2.7)

**Comment by anishmac99** [comment]
+1

**Comment by hsoft** [comment]
Hum, strange. I can't reproduce on my machine.

When looking around, I see tickets like https://github.com/SethMMorton/natsort/issues/8 or https://github.com/WoLpH/portalocker/issues/21 which point to some random issues, possibly being caused by the wheel not being universal (py2 and py3).

In the case of num2words, we use 2to3, so it can't be universal.

For the time being, I've removed the wheel from pypi and kept only the tar.gz. @ypraveen @anishmac99 does it work better now?

**Comment by ypraveen** [comment]
Works now. thanks!
